#!/usr/bin/bash

#URL of this file
#https://git.io/fjVcp

if [[ ! -f /usr/bin/stow ]]; then
    echo "you need to do: sudo pacman -S stow" >&2 && exit
fi

if [[ ! -f /usr/bin/xdg-user-dirs-update ]]; then
    echo "you need to do: sudo pacman -S xdg-user-dirs" >&2 && exit
fi

dotfilesurl=https://github.com/rpuntaie/dotfiles
cd ~

if [[ -d dotfiles ]]; then
  cd dotfiles
  if [[ ! "$(git config --get remote.origin.url)"=="$dotfilesurl" ]]; then
    echo "This install script is for a different dotfiles" >&2
    exit 1
  fi
  cd ~
  bash ~/dotfiles/bin/restowdots
else
  #if .dotfiles exits: $new_install=true ~/dotfiles/install
  new_install=true
  git clone $dotfilesurl
  bash ~/dotfiles/bin/restowdots -S
fi

if [[ -n $new_install ]] && $new_install; then
  fc-cache -fv
  bash ~/dotfiles/bin/my_python
  NPM_CONFIG_PREFIX=~/.local/var/lib/npm bash ~/dotfiles/bin/my_nodejs
  rsync -a ~/dotfiles/etc/weechat/ ~/.local/var/lib/weechat/
  mkdir -p ~/.local/var/lib/weechat/ssl
  cd ~/.local/var/lib/weechat/ssl
  openssl req -nodes -newkey rsa:2048 -keyout relay.pem -x509 -days 365 -out relay.pem -subj "/C=AT/ST=AT/L=AT/O=ME/OU=IT/CN=me.org"
fi

echo -e "\033[0;32mLog out and in, to activate the environment.
First time vim and zsh will install plugins."

#rollarch interprets lines starting with "^#PKG: ", "^#REPO: " and "^#DFN: ".

#DFN: KM=us
#DFN: CL=99
#DFN: LA_NG="de_DE ru_RU"
#DFN: ZONE=Vienna
#DFN: AIP2=1.108

#rpuntaie-meta needs about 40GB disk space
#rpuntaie-meta on https://github.com/rpuntaie/rollarch
#rollarch rpuntaie-meta is served from another Arch on the LAN via AIP2
#PKG: rpuntaie-meta

##else with less packages ##-># and add a # above
##PKG: base
##PKG: base-devel
##PKG: hwinfo
##PKG: nfs-utils
##PKG: devtools
##PKG: dialog
##PKG: wpa_supplicant
##PKG: ifenslave
##PKG: ifplugd
##PKG: ntp
##PKG: stow
##PKG: ripgrep
##PKG: fd
##PKG: bc
##PKG: tmux
##PKG: wget
##PKG: fzf
##PKG: udisks2
##PKG: unzip
##PKG: pacman-contrib
##PKG: bat
##PKG: ncdu
##PKG: the_silver_searcher
##PKG: p7zip
##PKG: ranger
##PKG: mtpfs
##PKG: pass
##PKG: openssh-askpass
##PKG: lsof
##PKG: systemd-resolvconf
##PKG: cscope
##PKG: ctags
##PKG: llvm
##PKG: gdb
##PKG: zsh-syntax-highlighting
##PKG: zsh-autosuggestions
##PKG: zsh-completions
##PKG: zsh-history-substring-search
##PKG: neovim
##PKG: vim-spell-en
##PKG: python-scipy
##PKG: python-sympy
##PKG: python-matplotlib
##PKG: python-pip
##PKG: python-mock
##PKG: python-pytest-mock
##PKG: python-pytest-cov
##PKG: python-wheel
##PKG: python-pandas
##PKG: python-lxml
##PKG: python-pyx
##PKG: python-bottle
##PKG: python-cairosvg
##PKG: python-click
##PKG: python-doit
##PKG: ipython
##PKG: pandoc
##PKG: alsa-utils
##PKG: pulseaudio-alsa
##PKG: pulsemixer
##PKG: xf86-video-intel
##PKG: xorg-server
##PKG: xorg-apps
##PKG: ibus-libpinyin
##PKG: ibus-m17n
##PKG: xdg-user-dirs
##PKG: wmctrl
##PKG: xmonad-contrib
##PKG: urxvt-perls
##PKG: xorg-xinit
##PKG: dmenu
##PKG: scrot
##PKG: slock
##PKG: libnotify
##PKG: dunst
##PKG: dex
##PKG: inkscape
##PKG: vlc
##PKG: firefox
##PKG: links
##PKG: browserpass-firefox
##PKG: eom
##PKG: feh
##PKG: zathura-djvu
##PKG: zathura-pdf-mupdf
##PKG: gvim
##PKG: boost
##PKG: cmake
##PKG: meson

