#! /bin/sh

# Screens
xrandr --output eDP-1 --pos 0x0
xrandr --output DP-1 --mode 2560x1080 --pos 1920x0

# Workspaces
bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor DP-1 -d 6 7 8 9 0

# top bar
bspc config -m eDP-1 top_padding 0
bspc config -m DP-1 top_padding 23
killall tint3
tint3 -c $HOME/.config/tint3/tint3rc-home

# Wallpaper
nitrogen --restore
