#! /bin/sh

# Screens
#xrandr --output eDP1 --mode 1600x900
xrandr --output DP-1 --off
xrandr --output DP-2 --off
xrandr --output HDMI-1 --off

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# top bar
bspc config -m eDP-1 top_padding          23
nitrogen --restore
killall tint3
tint3


