#!/usr/bin/env sh
# Environment set when logging into a shell.

#--------#
# {PATH} #
#--------#

# Adds directory to the PATH variable, with (hopefully) all necessary checks:
add_to_path() {
    [ -d "$1" ] || return
    [ -z "$PATH" ] && PATH="$1" && return
    IFS_OLD="$IFS"
    IFS=:
    for i in $PATH; do
        [ "$1" = "$i" ] && return
        [ -h "$1" ] && [ "$(readlink -f "$1")" = "$i" ] && return
    done
    PATH="$1:$PATH"
    IFS="$IFS_OLD"
    unset IFS_OLD
}

# User specific path:
add_to_path "$HOME/.local/bin"
add_to_path "$HOME/.local/opt/utils/bin"
add_to_path "$HOME/.local/opt/epfl-scripts/bin"

unset -f add_to_path
export PATH

# Kiex
test -s "$HOME/.kiex/scripts/kiex" && source "$HOME/.kiex/scripts/kiex"

#-------#
# {ENV} #
#-------#

# Perl-related stuff
export PERL_CPANM_OPT="--prompt --reinstall -l ~/.local/lib/perl5 --mirror http://cpan.cpantesters.org"
PERL5LIB=~/.local/lib/perl5/lib/perl5; export PERL5LIB

#------------------------#
# {Default Applications} #
#------------------------#

# Editor and pager:
export EDITOR='/usr/bin/vim'
export VISUAL='xvim'
export BROWSER="/usr/bin/qutebrowser"
