#! /bin/sh

bspconf="/home/fnux/.config/bspwm/"

# Basic Configuration
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer       true
bspc config focused_border_color    "#a6a28c"
bspc config active_border_color     "#7d7a68"
bspc config presel_feedback_color   "#6e6b5e"
bspc config normal_border_color     "#6e6b5e"

xrandr --output eDP1 --mode 1600x900 --pos 680x1200

bspc monitor eDP1 -d 1 2 3 4 5

# Specific configuration
sh $bspconf$1

# Background
nitrogen --restore
