#! /bin/sh

# Screens
xrandr --output DP2 --mode 1920x1200 --pos 0x0
xrandr --output DP1 --mode 2560x1080 --pos 1920x120
xrandr --output eDP1 --mode 1600x900 --pos 680x1200

# Workspaces
bspc monitor DP1 -d 1 2 3 4 5
bspc monitor DP2 -d 1 2 3 4 5

# top bar
bspc config -m DP2 top_padding 23
tint3 -c $HOME/.config/tint3/tint3rc_home &
