#! /bin/sh

# Screens
output VIRTUAL1 --off --output eDP1 --mode 1600x900 --pos 0x180 --rotate normal --output DP1 --mode 2560x1080 --pos 1600x0 --rotate normal --output HDMI2 --off --output HDMI1 --off --output DP2 --off

# Workspaces
bspc monitor DP1 -d 1 2 3 4 5
bspc monitor DP2 -d 1 2 3 4 5

# top bar
bspc config -m eDP1 top_padding 0
bspc config -m DP1 top_padding 23
tint3 -c $HOME/.config/tint3/tint3rc
