#! /bin/sh

# Screens
xrandr --output eDP1 --mode 1600x900 --pos 0x180
xrandr --output DP2 --mode 1920x1080 --pos 1600x0

# Workspaces
bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor DP2 -d 6 7 8 9 0

# top bar
bspc config -m eDP1 top_padding 0
bspc config -m DP2 top_padding 23
tint3 -c $HOME/.config/tint3/tint3rc-home
