#! /bin/sh

# Monfigure Monitor
xrandr --output eDP1 --mode 1600x900 
xrandr --output DP1 --off
xrandr --output DP2 --off 

# Configure BSPWM
bspc config border_width        2
bspc config window_gap         8

bspc config -m eDP1 top_padding          23

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer       true
bspc config focused_border_color    "#a6a28c"
bspc config active_border_color     "#7d7a68"
bspc config normal_border_color     "#6e6b5e"

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 

# Menu Bar
tint3 -c $HOME/.config/tint3/tint3rc &

# Background
nitrogen --restore

