#! /bin/sh

# Basic Configuration
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer       true
#bspc config focused_border_color    "#a6a28c"
bspc config focused_border_color    "#8E2803"
bspc config active_border_color     "#7d7a68"
bspc config presel_feedback_color   "#6e6b5e"
bspc config normal_border_color     "#6e6b5e"

bspc rule -a Thunderbird desktop='^10'
bspc rule -a TelegramDesktop desktop='^9'
bspc rule -a Gajim desktop='^9'
bspc rule -a Gcolor3 state=floating 

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10

# Top panel
bspc config top_padding 23
mkfifo /tmp/xmobar-fifo
bspc subscribe desktop | xmobar-bspwm-workspaces &
xmobar &
