#!/usr/bin/env sh
# Configuration for interactive shells.

###########
# Helpers #
###########

cmd_exists()
{
	for c in $@; do
		which $c >/dev/null 2>&1 || return -1
	done
}

###########
# Aliases #
###########

alias cp='cp -i'
alias grep='grep --color=auto'
alias info='info --vi-keys'
alias la='ls -A'
alias lah='ls -lAh'
alias laht='ls -lAht'
alias ll='ls -lh'
alias mv='mv -i'
alias ls='ls --color=auto'
alias vim='vim -u ~/.config/vim/vimrc'
alias scrot='scrot ~/Pictures/Screenshots/%Y-%m-%d-%T-screenshot.png'
alias wttr='curl wttr.in'
alias moon='curl wttr.in/Moon'
alias mpd='mpd ~/.config/mpd/mpd.conf'
alias fuck='sudo $(history -p \!\!)' 
alias clock='tty-clock -s -c -C 3'
alias yay='yaourt'
alias steam="LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' steam"

# Application specific aliases:
cmd_exists ncmpcpp && alias ncmpcpp='ncmpcpp -c ~/.config/ncmpcpp/config'
cmd_exists startx && alias startx="startx $XINITRC"

# Pass user environment when launching vim with sudo:
if cmd_exists sudo; then
	sudo()
	{
		if { [ "$1" = 'vim' ] || [ "$1" = 'vimdiff' ] || [ "$1" = 'visudo' ]; }\
		&& cmd_exists "$1"; then
			command sudo -E "$@"
		else
			command sudo "$@"
		fi
	}
fi

# Server only aliases (mostly additional security):
if [ -n "$SSH_CONNECTION" ]; then
	alias rm='rm -i'
fi

# In zsh vim mode, I sometimes forget I'm not in vim:
alias :e="$EDITOR"
alias :q=exit

##########
# Prompt #
##########

# Prompt colours:
pc_vcs_kernel=$(printf "\033[1;30m")
pc_vcs_clean=$(printf "\033[32m")
pc_vcs_ahead=$(printf "\033[36m")
pc_vcs_ready=$(printf "\033[33m")
pc_vcs_dirty=$(printf "\033[31m")
pc_vcs_merge=$(printf "\033[1;31m")
pc_host=$(printf "\033[35m")
pc_pwd=$(printf "\033[34m")
pc_prompt=$(printf "\033[1;31m")
pc_jobs=$(printf "\033[47;30m")
