#!/usr/bin/env sh
# Environment set when logging into a shell.

#--------#
# {PATH} #
#--------#

# Adds directory to the PATH variable, with (hopefully) all necessary checks:
add_to_path() {
    [ -d "$1" ] || return
    [ -z "$PATH" ] && PATH="$1" && return
    IFS_OLD="$IFS"
    IFS=:
    for i in $PATH; do
        [ "$1" = "$i" ] && return
        [ -h "$1" ] && [ "$(readlink -f "$1")" = "$i" ] && return
    done
    PATH="$1:$PATH"
    IFS="$IFS_OLD"
    unset IFS_OLD
}

# User specific path:
add_to_path "$HOME/.local/bin"
add_to_path "$HOME/.local/scripts"
add_to_path "$HOME/.gem/ruby/2.3.0/bin/"

unset -f add_to_path
export PATH

#-------#
# {ENV} #
#-------#

# Works better
TERM=xterm

# Perl-related stuff
export PERL_CPANM_OPT="--prompt --reinstall -l ~/.local/lib/perl5 --mirror http://cpan.cpantesters.org"
PERL5LIB=~/.local/lib/perl5/lib/perl5; export PERL5LIB

#-------#
# {XDG} #
#-------#

# Set XDG variables:
#export XDG_CONFIG_HOME=~/.config
#export XDG_CACHE_HOME=~/.cache
#export XDG_DATA_HOME=~/.local/share

export VIMINIT="source ~/.config/vim/vimrc"        # vim
export XINITRC="~/.config//X11/xinitrc"             # xinit (!startx)
#export XRESOURCES="~/.config/X11/Xresources"
#export XAUTHORITY="~/.config/X11/Xauthority"        # startx
#export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"                 # gpg
#export PASSWORD_STORE_DIR="$XDG_DATA_HOME/pass"           # pass
#export GIMP2_DIRECTORY="$XDG_CONFIG_HOME/gimp"            # gimp
#export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0" # GTK+

#------------------------#
# {Default Applications} #
#------------------------#

# Editor and pager:
export EDITOR='/usr/bin/vim'
export VISUAL='/usr/bin/vim'
export BROWSER="firefox"

#--------#
# {Look} #
#--------#

if [ "$TERM" = 'linux' ]; then
    export LESS_TERMCAP_mb=$(printf "\033[34m")
    export LESS_TERMCAP_md=$(printf "\033[31m")
    export LESS_TERMCAP_me=$(printf "\033[0m")
    export LESS_TERMCAP_se=$(printf "\033[0m")
    export LESS_TERMCAP_so=$(printf "\033[30;43m")
    export LESS_TERMCAP_ue=$(printf "\033[0m")
    export LESS_TERMCAP_us=$(printf "\033[32m")
else
    export LESS_TERMCAP_mb=$(printf "\033[1;34m")
    export LESS_TERMCAP_md=$(printf "\033[38;5;9m")
    export LESS_TERMCAP_me=$(printf "\033[0m")
    export LESS_TERMCAP_se=$(printf "\033[0m")
    export LESS_TERMCAP_so=$(printf "\033[30;43m")
    export LESS_TERMCAP_ue=$(printf "\033[0m")
    export LESS_TERMCAP_us=$(printf "\033[38;5;10m")
fi
