#!/bin/bash

startx="/usr/bin/startx"

bspwm="$HOME/.config/X11/bspwm"
xfce="$HOME/.config/X11/xfce"
xmonad="$HOME/.config/X11/xmonad"

if [ $# != 1 ]
then
  $startx $bspwm
elif [ $1 == "xfce" ]
then
  $startx $xfce
elif [ $1 == "xmonad" ]
  then
      $startx $xmonad
else
  $startx $1
fi
