#!/bin/sh

# Disable beep stuff
xset -b

# Load X resources:
xrdb ~/.config/X11/Xresources

# swap escape and caps lock
setxkbmap -model pc104 -layout ch -option caps:swapescape

# Set the wallpaper:
nitrogen --restore

# Start gpg-agent
gpg-connect-agent /bye >/dev/null 2>&1
# Set SSH to use gpg-agent
export SSH_AUTH_SOCK="${HOME}/.gnupg/S.gpg-agent.ssh"
# Set GPG TTY
GPG_TTY=$(tty)
export GPG_TTY

unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
    export SSH_AUTH_SOCK="/run/user/$UID/gnupg/S.gpg-agent.ssh"
fi

# Load keybindings
sxhkd &

# Launch yeahconsole
yeahconsole &

# Enable Japanese input:
#if [ -e /usr/bin/uim-xim ]; then
#	export GTK_IM_MODULE=uim
#	export QT_IM_MODULE=xim
#	uim-xim &
#	export XMODIFIERS='@im=anthy'
#fi

# Dunst notification daemon
#dunst &

# Cursor
xsetroot -cursor_name left_ptr

# Adapt the display's color to the time of the day
xflux -l 46.5 -g 6.6

# Launch
exec startxfce4
