#!/bin/sh

# SERVICES ---------------------------------------------------------------------

# Load X resources:
xrdb ~/.config/X11/Xresources

# swap escape and caps lock

setxkbmap -model pc104 -layout ch -option caps:swapescape

# Set the wallpaper:
nitrogen --restore

# Start gpg-agent
 gpg-connect-agent /bye >/dev/null 2>&1
# Set SSH to use gpg-agent
export SSH_AUTH_SOCK="${HOME}/.gnupg/S.gpg-agent.ssh"
# Set GPG TTY
GPG_TTY=$(tty)
export GPG_TTY
#
# Load keybindings
sxhkd &

# Enable Japanese input:
#if [ -e /usr/bin/uim-xim ]; then
#	export GTK_IM_MODULE=uim
#	export QT_IM_MODULE=xim
#	uim-xim &
#	export XMODIFIERS='@im=anthy'
#fi

# WM ---------------------------------------------------------------------------

# Cursor
xsetroot -cursor_name left_ptr

# Start the compositor
compton -D 0 --no-fading-openclose --config ~/.config/compton/compton.conf -b &

# Adapt the display's color to the time of the day
xflux -l 46.5 -g 6.6

# Launch WM
exec bspwm -c /home/fnux/.config/bspwm/bspwmrc
