#!/bin/sh

if test -z "$DBUS_SESSION_BUS_ADDRESS" ; then
  eval `dbus-launch --sh-syntax`
fi

# Cursor
xsetroot -cursor_name left_ptr

# Dunst notification daemon
dunst &

# Fix GUI for java apps
export _JAVA_AWT_WM_NONREPARENTING=1

if [[ -n $(grep "^flags.*\ hypervisor\ " /proc/cpuinfo) ]]; then
  VBoxClient-all &
fi

setxkbmap -option terminate:ctrl_alt_bksp

xrdb -load $XDG_CONFIG_HOME/X11/Xresources

#Caps_Lock to Print
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape' -e 'keysym Print = Caps_Lock'

#needs to go before WM
dex --environment $WM --autostart --search-paths $XDG_CONFIG_HOME/autostart

ibus-daemon --xim -d -r &
#switch with (works with pluma)
#ibus engine libpinyin
#ibus engine xkb:us::eng

# Launch WM
if [ -z "$WM" ]; then
  export WM=xmonad
fi
exec $WM


